import Colors from "@/constants/Colors";
import { TypographyThemes } from "@/constants/Fonts";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background.primary,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[200],
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerTitle: {
    ...TypographyThemes.poppins.subtitle,
    fontSize: 20,
    fontWeight: "700",
    color: Colors.text.primary,
  },
  closeButton: {
    backgroundColor: Colors.red[500],
    width: 32,
    height: 32,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: Colors.red[500],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },

  // Summary Card
  summaryCard: {
    backgroundColor: Colors.blue[50],
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: Colors.blue[200],
    elevation: 3,
    shadowColor: Colors.blue[500],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 12,
  },
  summaryTitle: {
    ...TypographyThemes.poppins.subtitle,
    fontSize: 18,
    fontWeight: "700",
    color: Colors.blue[700],
  },
  summaryDetails: {
    gap: 12,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: Colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.blue[100],
  },
  summaryLabel: {
    ...TypographyThemes.nunito.body,
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text.secondary,
  },
  summaryValue: {
    ...TypographyThemes.nunito.body,
    fontSize: 16,
    fontWeight: "700",
    color: Colors.blue[600],
  },
  summaryTotalValue: {
    ...TypographyThemes.nunito.body,
    fontSize: 18,
    fontWeight: "700",
    color: Colors.green[600],
  },

  // Product List
  productList: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  productCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 20,
    marginVertical: 6,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: Colors.border.light,
  },
  productHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  productName: {
    ...TypographyThemes.poppins.subtitle,
    fontSize: 18,
    fontWeight: "600",
    color: Colors.text.primary,
    flex: 1,
    marginRight: 12,
  },
  quantityBadge: {
    backgroundColor: Colors.blue[100],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.blue[200],
  },
  quantityText: {
    ...TypographyThemes.nunito.body,
    fontSize: 14,
    fontWeight: "700",
    color: Colors.blue[700],
  },
  productDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  detailLabel: {
    ...TypographyThemes.nunito.body,
    fontSize: 14,
    color: Colors.text.secondary,
    marginLeft: 6,
    marginRight: 4,
  },
  detailValue: {
    ...TypographyThemes.nunito.body,
    fontSize: 14,
    fontWeight: "600",
    color: Colors.text.primary,
  },
  expirationContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border.light,
  },
  expirationText: {
    ...TypographyThemes.nunito.body,
    fontSize: 13,
    color: Colors.text.secondary,
    marginLeft: 6,
  },

  // Empty State
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingVertical: 64,
  },
  emptyText: {
    ...TypographyThemes.nunito.body,
    fontSize: 16,
    color: Colors.text.secondary,
    textAlign: "center",
    lineHeight: 24,
    marginTop: 16,
  },
});
