import Colors from "@/constants/Colors";
import { Fonts, TypographyThemes } from "@/constants/Fonts";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 10,
    paddingHorizontal: 16,
  },
  searchContainer: {
    marginBottom: 16,
  },
  loadingMore: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
  },
  loadingMoreText: {
    ...TypographyThemes.nunito.body,
    color: Colors.text.secondary,
    marginLeft: 8,
    fontSize: 14,
  },
  loadMoreButton: {
    backgroundColor: Colors.blue.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    gap: 8,
  },
  loadMoreButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  loadMoreButtonDisabled: {
    backgroundColor: Colors.gray[300],
    opacity: 0.6,
  },
  loadMoreButtonTextDisabled: {
    color: Colors.gray[500],
  },
  listContainer: {
    flex: 1,
  },
  listContent: {
    flexGrow: 1,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: Colors.whiteSemiTransparent,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    shadowColor: Colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: Colors.red[500],
  },
  itemNumber: {
    fontSize: 24,
    fontFamily: Fonts.MontserratBold,
    fontWeight: "700",
    color: Colors.gray[100],
    marginRight: 16,
    minWidth: 40,
    textAlign: "center",
    backgroundColor: Colors.red[500],
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 12,
    alignSelf: "flex-start",
    marginTop: 2,
  },
  itemData: {
    flex: 1,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  mainDataContainer: {
    flex: 1,
    marginRight: 16,
  },
  mainDataLabel: {
    ...TypographyThemes.nunito.caption,
    color: Colors.text.secondary,
    fontSize: 11,
    marginBottom: 1,
  },
  mainDataValue: {
    fontSize: 16,
    fontFamily: Fonts.PoppinsSemiBold,
    fontWeight: "600",
    color: Colors.text.primary,
  },
  amountContainer: {
    alignItems: 'flex-end',
  },
  amountLabel: {
    ...TypographyThemes.nunito.caption,
    color: Colors.text.secondary,
    fontSize: 11,
    marginBottom: 1,
  },
  amountValue: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.red[600],
    fontSize: 16,
    fontWeight: "700",
  },
  methodContainer: {
    alignItems: 'flex-end',
    marginTop: 4,
  },
  methodLabel: {
    ...TypographyThemes.nunito.caption,
    color: Colors.text.secondary,
    fontSize: 10,
    marginBottom: 1,
  },
  methodValue: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.blue[600],
    fontSize: 12,
    fontWeight: "600",
  },
  detailsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.red[500],
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.red[600],
  },
  detailsButtonText: {
    ...TypographyThemes.nunito.body,
    color: Colors.white,
    fontSize: 13,
    fontWeight: "600",
  },
  emptyStateContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyStateText: {
    ...TypographyThemes.nunito.body,
    color: Colors.text.secondary,
    textAlign: "center",
    marginTop: 12,
    fontSize: 16,
  },
  emptyStateSubtext: {
    ...TypographyThemes.nunito.body,
    color: Colors.text.secondary,
    textAlign: "center",
    marginTop: 8,
    fontSize: 14,
    opacity: 0.7,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  loadingText: {
    ...TypographyThemes.nunito.body,
    color: Colors.text.secondary,
    marginTop: 12,
  },
  dateContainer: {
    alignItems: 'flex-end',
    marginTop: 4,
  },
  dateLabel: {
    ...TypographyThemes.nunito.caption,
    color: Colors.text.secondary,
    fontSize: 10,
    marginBottom: 1,
  },
  dateValue: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.gray[600],
    fontSize: 11,
    fontWeight: "500",
  },
  fabContainer: {
    position: "absolute",
    bottom: 24,
    right: 16,
  },
  fabButton: {
    backgroundColor: Colors.red[500],
    width: 68,
    height: 68,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.red[500],
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
});