import Colors from "@/src/constants/Colors";
import { StyleSheet } from "react-native";

const cornerSize = 20;
const borderWidth = 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  heroImage: {
    position: "absolute",
    top: 80,
    right: -270,
    width: "130%",
    height: "95%",
    transform: [{ scaleX: -1 }],
    resizeMode: "cover",
    opacity: 0.1,
    zIndex: -1,
  },
  previewBalence: {
    position: "relative",
    paddingHorizontal: 24,
    paddingVertical: 10,
    marginTop: 15,
  },
  totalValue: {
    fontSize: 35,
    fontWeight: "bold",
    color: Colors.blue.light,
    textAlign: "center",
  },
  cornerTopLeft: {
    position: "absolute",
    top: 0,
    left: 0,
    width: cornerSize,
    height: cornerSize,
    borderTopWidth: borderWidth,
    borderLeftWidth: borderWidth,
    borderColor: Colors.blue.light,
    borderTopLeftRadius: 6,
  },
  cornerBottomRight: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: cornerSize,
    height: cornerSize,
    borderBottomWidth: borderWidth,
    borderRightWidth: borderWidth,
    borderColor: Colors.blue.light,
    borderBottomRightRadius: 6,
  },
  cashierDetails: {
    justifyContent: "center",
    flexDirection: "row",
    gap: 40,
    marginTop: 5,
  },
  entries: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  icon: {
    alignItems: "center",
    justifyContent: "center",
    width: 35,
    height: 35,
    borderWidth: 1,
    borderRadius: 5,
    borderColor: Colors.blue.light,
  },
  Number: {
    fontSize: 18,
    fontWeight: "900",
  },
  Label: {
    fontSize: 13,
    color: Colors.blue.light,
    fontWeight: "700",
  },
  exits: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  body: {
    width: "100%",
    marginVertical: 5,
  },
  scrollContent: {
    paddingBottom: 5,
    alignItems: "center",
    flexGrow: 1,
  },
  list: {
    marginTop: 5,
    backgroundColor: "transparent",
    width: "95%",
  },
  listContent: {
    paddingBottom: 20,
  },
  transactionList: {
    width: "90%",
    marginTop: 20,
    gap: 12,
  },
  transactionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderRadius: 10,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 4,
    elevation: 2,
  },
  transactionIcon: {
    width: 50,
    height: 50,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  transactionInfo: {
    flex: 1,
    marginLeft: 12,
  },
  transactionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
  },
  transactionSubtitle: {
    fontSize: 13,
    color: Colors.blue.light,
  },
  transactionValueSNeutral: {
    fontSize: 17,
    fontWeight: "bold",
    color: Colors.black,
  },
  transactionValue: {
    fontSize: 17,
    fontWeight: "bold",
    color: Colors.green[300],
  },
  transactionValueExit: {
    fontSize: 17,
    fontWeight: "bold",
    color: Colors.red[300],
  },
  buttonContainer: {
    alignItems: "center",
    width: "90%",
    marginTop: "auto",
  },
  button: {
    backgroundColor: Colors.red[500],
    width: "100%",
  },
  bottomBar: {
    height: "12%",
    width: "100%",
    backgroundColor: Colors.gray.zinc,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: Colors.gray.medium,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderTopRightRadius: 42,
    borderTopLeftRadius: 42,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
});
