import Colors from "@/src/constants/Colors";
import { TypographyThemes } from "@/src/constants/Fonts";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  infoContainer: {
    marginTop: 5,
    padding: 20,
    backgroundColor: Colors.blue.primary,
    marginBottom: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.blue.light,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoIconContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 8,
    marginRight: 12,
  },
  infoTitle: {
    ...TypographyThemes.poppins.subtitle,
    fontWeight: '700',
    color: Colors.white,
  },
  infoDescription: {
    ...TypographyThemes.nunito.bodySmall,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 22,
  },
  section: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    paddingHorizontal: 24,
    paddingVertical: 20,
    marginVertical: 6,
    shadowColor: Colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: Colors.border.light,
  },
  sectionTitle: {
    ...TypographyThemes.poppins.subtitle,
    color: Colors.text.primary,
    marginBottom: 8,
    fontWeight: '600',
    fontSize: 16,
  },
  sectionDescription: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.text.secondary,
    marginBottom: 20,
    lineHeight: 18,
    fontSize: 13,
  },
  periodInfo: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.text.primary,
    marginBottom: 16,
    fontStyle: 'italic',
    backgroundColor: Colors.blue[50],
    padding: 16,
    borderRadius: 12,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: Colors.blue[100],
    fontSize: 13,
  },
  optionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  optionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: Colors.blue[200],
    backgroundColor: Colors.white,
    width: '48%',
    shadowColor: Colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  optionButtonSelected: {
    backgroundColor: Colors.blue.primary,
    borderColor: Colors.blue.primary,
    shadowColor: Colors.shadow.colored,
    shadowOpacity: 0.15,
    elevation: 6,
  },
  optionButtonDisabled: {
    backgroundColor: Colors.gray[100],
    borderColor: Colors.gray[200],
    opacity: 0.6,
  },
  optionContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionText: {
    ...TypographyThemes.poppins.bodySmall,
    color: Colors.blue.primary,
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  optionTextSelected: {
    color: Colors.white,
  },
  optionTextDisabled: {
    color: Colors.gray[500],
  },
  optionDescription: {
    ...TypographyThemes.openSans.caption,
    color: Colors.text.secondary,
    fontSize: 12,
    lineHeight: 16,
  },
  optionDescriptionSelected: {
    color: Colors.white,
    opacity: 0.9,
  },
  switchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  switchInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  switchLabel: {
    ...TypographyThemes.poppins.bodySmall,
    color: Colors.text.primary,
    fontWeight: '500',
    fontSize: 14,
  },
  dateContainer: {
    marginBottom: 16,
  },
  dateLabel: {
    ...TypographyThemes.poppins.bodySmall,
    color: Colors.text.secondary,
    marginBottom: 8,
    fontWeight: '500',
    fontSize: 13,
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border.medium,
    backgroundColor: Colors.white,
    shadowColor: Colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  dateButtonText: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.text.primary,
    fontSize: 14,
  },
  dateButtonDisabled: {
    backgroundColor: Colors.gray[100],
    borderColor: Colors.gray[200],
  },
  dateButtonTextDisabled: {
    color: Colors.gray[500],
  },
  chartsContainer: {
    gap: 12,
  },
  chartOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: Colors.blue[200],
    backgroundColor: Colors.white,
    gap: 12,
    shadowColor: Colors.shadow.light,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  chartOptionSelected: {
    backgroundColor: Colors.blue.primary,
    borderColor: Colors.blue.primary,
    shadowColor: Colors.shadow.colored,
    shadowOpacity: 0.15,
    elevation: 6,
  },
  chartOptionText: {
    ...TypographyThemes.poppins.bodySmall,
    color: Colors.blue.primary,
    fontWeight: '500',
    flex: 1,
    fontSize: 14,
  },
  chartOptionTextSelected: {
    color: Colors.white,
  },
  generateButtonContainer: {
    paddingVertical: 20,
    paddingBottom: 40,
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.blue.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  generateButtonText: {
    ...TypographyThemes.openSans.button,
    color: Colors.white,
    fontWeight: '600',
    fontSize: 16,
  },
  generateButtonDisabled: {
    backgroundColor: Colors.gray[300],
    shadowOpacity: 0,
    elevation: 0,
  },
  generateButtonTextDisabled: {
    color: Colors.gray[500],
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 400,
    shadowColor: Colors.shadow.dark,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border.light,
  },
  modalTitle: {
    ...TypographyThemes.poppins.subtitle,
    color: Colors.text.primary,
    fontWeight: '600',
    fontSize: 18,
    flex: 1,
  },
  closeButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: Colors.gray[100],
  },
  rangeInfo: {
    marginTop: 16,
    padding: 12,
    backgroundColor: Colors.blue[50],
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.blue[100],
  },
  rangeInfoText: {
    ...TypographyThemes.openSans.bodySmall,
    color: Colors.text.primary,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.border.light,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.gray[300],
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    ...TypographyThemes.poppins.bodySmall,
    color: Colors.text.secondary,
    fontWeight: '500',
    fontSize: 14,
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: Colors.blue.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.shadow.colored,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  confirmButtonText: {
    ...TypographyThemes.poppins.bodySmall,
    color: Colors.white,
    fontWeight: '600',
    fontSize: 14,
  },
});