import { StyleSheet } from "react-native";
import Colors from "@/src/constants/Colors";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    backgroundColor: "transparent",
    height: 120,
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomRightRadius: 70,
    paddingHorizontal: 10,
  },
  brandContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginBottom: 10,
  },
  titleHeader: {
    fontSize: 30,
    fontWeight: "bold",
    color: Colors.gray[50],
    textTransform: "uppercase",
    includeFontPadding: false,
    textAlignVertical: "center",
  },
  iconCircle: {
    width: 50,
    height: 50,
    borderRadius: 30,
    backgroundColor: Colors.gray.zinc,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginBottom: 10,
  },
  container: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 16,
    marginBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: Colors.blue.dark,
    marginBottom: 20,
    textAlign: "center",
  },
  chartContainer: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.blue.dark,
    marginBottom: 4,
    marginLeft: 5,
  },
  chart: {
    borderRadius: 8,
  },
  summaryContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 24,
  },
  summaryItem: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 16,
    width: "48%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryLabel: {
    fontSize: 14,
    color: Colors.gray.dark,
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: Colors.blue.dark,
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 5,
  },
  summarySubText: {
    fontSize: 12,
    color: Colors.gray.dark,
    marginTop: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.white,
  },
  loadingText: {
    marginTop: 10,
    color: Colors.blue.dark,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: Colors.white,
  },
  errorText: {
    color: Colors.red[500],
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 20,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: Colors.blue.dark,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 10,
  },
  retryButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: "600",
  },
  emptySubtext: {
    fontSize: 14,
    color: Colors.gray.dark,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  progressContainer: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    height: 220,
    backgroundColor: Colors.white,
    borderRadius: 8,
  },
  progressChart: {
    position: "absolute",
    borderRadius: 8,
    backgroundColor: Colors.white,
  },
  progressTextContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  progressPercentage: {
    fontSize: 32,
    fontWeight: "bold",
    color: Colors.blue.dark,
    textAlign: "center",
  },
  progressLabel: {
    fontSize: 14,
    color: Colors.gray.dark,
    marginTop: -5,
  },
  progressAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.gray.dark,
    textAlign: "left",
    marginLeft: 10,
    opacity: 0.8,
  },
  motivationalText: {
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 8,
    fontStyle: "italic",
  },
chartHeader: {
  flexDirection: 'column',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  marginBottom: 8,
  marginLeft: 5,
},
toggleButton: {
  backgroundColor: Colors.blue.light,
  paddingHorizontal: 12,
  paddingVertical: 6,
  borderRadius: 15,
},
toggleButtonText: {
  fontSize: 12,
  fontWeight: '600',
  color: Colors.white,
},
switchContainer: {
  alignSelf: 'flex-end',
  flexDirection: 'row',
  alignItems: 'center',
  gap: 8,
},
switch: {
  width: 50,
  height: 28,
  borderRadius: 15,
  backgroundColor: Colors.gray[300],
  padding: 2,
  justifyContent: 'center',
  position: 'relative',
},
switchActive: {
  backgroundColor: Colors.blue.dark,
},
switchToggle: {
  width: 24,
  height: 24,
  borderRadius: 12,
  backgroundColor: Colors.white,
  position: 'absolute',
  left: 2,
},
switchToggleActive: {
  left: 24,
},
switchLabel: {
  fontSize: 12,
  color: Colors.gray.dark,
  fontWeight: '500',
},
activeLabel: {
  color: Colors.blue.dark,
  fontWeight: '600',
},
configWarningContainer: {
  backgroundColor: Colors.white,
  borderRadius: 10,
  padding: 20,
  marginHorizontal: 20,
  marginTop: 20,
  shadowColor: Colors.gray.dark,
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
configWarningTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  color: Colors.blue.dark,
  marginBottom: 10,
  textAlign: 'center',
},
configWarningText: {
  fontSize: 14,
  color: Colors.gray.dark,
  marginBottom: 20,
  textAlign: 'center',
},
configButton: {
  backgroundColor: Colors.blue.dark,
  paddingVertical: 12,
  borderRadius: 8,
  alignItems: 'center',
},
configButtonText: {
  color: Colors.white,
  fontWeight: 'bold',
  fontSize: 16,
},
});
