import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  formContainer: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 24,
    marginTop: 16,
    marginHorizontal: 16,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text.primary,
    marginBottom: 12,
    marginTop: 8,
  },
  input: {
    backgroundColor: Colors.gray[50],
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 16,
    color: Colors.text.primary,
    borderWidth: 2,
    borderColor: Colors.gray[200],
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  inputFocused: {
    borderColor: Colors.blue.primary,
    backgroundColor: Colors.white,
    shadowOpacity: 0.15,
  },
  description: {
    fontSize: 12,
    color: Colors.text.secondary,
    marginTop: 8,
    fontStyle: "italic",
  },
  inputRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  smallInput: {
    flex: 1,
  },
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 20,
    gap: 16,
  },
  cancelButton: {
    flex: 1,
    height: 56,
    borderRadius: 16,
  },
  updateButton: {
    flex: 1,
    height: 56,
    borderRadius: 16,
    backgroundColor: Colors.orange[500],
  },
  barcodeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  barcodeInput: {
    flex: 1,
    backgroundColor: Colors.gray[50],
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 16,
    color: Colors.text.primary,
    borderWidth: 2,
    borderColor: Colors.gray[200],
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  scanButton: {
    backgroundColor: Colors.blue.primary,
    width: 56,
    height: 56,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  scanButtonDisabled: {
    backgroundColor: Colors.gray[400],
    shadowOpacity: 0.1,
    elevation: 2,
  },
  dateInput: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "relative",
  },
  dateInputText: {
    fontSize: 16,
    color: Colors.text.primary,
    flex: 1,
    fontWeight: "500",
  },
  dateInputPlaceholder: {
    color: Colors.gray[400],
    fontWeight: "400",
  },
  dateInputIcon: {
    backgroundColor: Colors.blue.primary,
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  dateInputFocused: {
    borderColor: Colors.blue.primary,
    backgroundColor: Colors.white,
    shadowOpacity: 0.15,
    transform: [{ scale: 1.02 }],
  },
  dateInputIconFocused: {
    backgroundColor: Colors.blue.logo,
    shadowOpacity: 0.3,
    transform: [{ scale: 1.1 }],
  },
});