import Colors from '@/constants/Colors';
import { Fonts } from '@/constants/Fonts';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  content: {
    flex: 1,
    padding: 20,
  },
  scrollContent: {
    paddingBottom: 30,
    flexGrow: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: Colors.gray[900],
    marginBottom: 8,
    fontFamily: Fonts.Roboto_700Bold,
  },
  subtitle: {
    fontSize: 16,
    color: Colors.gray[600],
    marginBottom: 24,
    fontFamily: Fonts.RobotoRegular,
  },
  goalsContainer: {
    gap: 16,
  },
  goalCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 20,
    shadowColor: Colors.gray[900],
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  goalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  goalIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.blue[100],
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  goalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.gray[900],
    fontFamily: Fonts.Roboto_600SemiBold,
  },
  goalDescription: {
    fontSize: 14,
    color: Colors.gray[600],
    marginTop: 4,
    fontFamily: Fonts.RobotoRegular,
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.gray[700],
    marginBottom: 8,
    fontFamily: Fonts.RobotoMedium,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.gray[300],
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: Colors.gray[900],
    backgroundColor: Colors.white,
    fontFamily: Fonts.RobotoRegular,
  },
  inputFocused: {
    borderColor: Colors.blue[500],
    shadowColor: Colors.blue[500],
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  currencyInput: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  currencySymbol: {
    fontSize: 16,
    color: Colors.gray[600],
    marginRight: 8,
    fontFamily: Fonts.RobotoMedium,
  },
  currencyInputField: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.gray[300],
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: Colors.gray[900],
    backgroundColor: Colors.white,
    fontFamily: Fonts.RobotoRegular,
  },
  currencyInputFocused: {
    borderColor: Colors.blue[500],
    shadowColor: Colors.blue[500],
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  toggleLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: Colors.gray[700],
    fontFamily: Fonts.RobotoMedium,
  },
  toggle: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: Colors.gray[300],
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleActive: {
    backgroundColor: Colors.blue[500],
  },
  toggleThumb: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: Colors.white,
    shadowColor: Colors.gray[900],
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleThumbActive: {
    transform: [{ translateX: 20 }],
  },
  buttonsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 24,
  },
  saveButton: {
    flex: 1,
    backgroundColor: Colors.blue[500],
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: Colors.blue[500],
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Fonts.Roboto_600SemiBold,
  },
  saveButtonDisabled: {
    backgroundColor: Colors.gray[300],
    shadowOpacity: 0,
    elevation: 0,
  },
  saveButtonTextDisabled: {
    color: Colors.gray[500],
  },
  deactivateButton: {
    flex: 1,
    backgroundColor: Colors.red[500],
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: Colors.red[500],
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  deactivateButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '600',
    fontFamily: Fonts.Roboto_600SemiBold,
  },
  deactivateButtonDisabled: {
    backgroundColor: Colors.gray[300],
    shadowOpacity: 0,
    elevation: 0,
  },
  deactivateButtonTextDisabled: {
    color: Colors.gray[500],
  },
  infoCard: {
    marginTop: 5,
    padding: 20,
    backgroundColor: Colors.blue.primary,
    marginBottom: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.blue.light,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoIconContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 8,
    marginRight: 12,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.white,
    fontFamily: Fonts.Roboto_700Bold,
  },
  infoText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 22,
    fontFamily: Fonts.RobotoRegular,
  },
  errorText: {
    fontSize: 12,
    color: Colors.red[500],
    marginTop: 4,
    fontFamily: Fonts.RobotoRegular,
  },
  successText: {
    fontSize: 12,
    color: Colors.green[500],
    marginTop: 4,
    fontFamily: Fonts.RobotoRegular,
  },
});
