import Colors from "@/src/constants/Colors";
import { TypographyThemes } from "@/src/constants/Fonts";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  // Card de boas-vindas
  welcomeCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 20,
    marginTop: 10,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  welcomeHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  welcomeIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.blue[500],
    justifyContent: "center",
    alignItems: "center",
  },
  welcomeInfo: {
    flex: 1,
  },
  welcomeTitle: {
    ...TypographyThemes.poppins.title,
    fontSize: 20,
    color: Colors.text.primary,
    marginBottom: 8,
  },
  welcomeDescription: {
    ...TypographyThemes.nunito.bodySmall,
    fontSize: 14,
    color: Colors.text.secondary,
    lineHeight: 20,
  },
  scanIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.green[50],
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.green[200],
  },
  scanText: {
    ...TypographyThemes.nunito.body,
    fontSize: 12,
    fontWeight: '700',
    color: Colors.green[700],
  },
  // Seção informativa
  infoContainer: {
    marginTop: 5,
    padding: 20,
    backgroundColor: Colors.blue.primary,
    marginBottom: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.blue.light,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoIconContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 8,
    marginRight: 12,
  },
  infoTitle: {
    ...TypographyThemes.poppins.subtitle,
    fontWeight: '700',
    color: Colors.white,
  },
  infoDescription: {
    ...TypographyThemes.nunito.bodySmall,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 22,
  },
  // Seções de informações
  section: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 10,
    marginTop: 16,
    marginBottom: 16,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    ...TypographyThemes.poppins.subtitle,
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text.primary,
    marginBottom: 12,
    paddingLeft: 2,
  },
  categoryContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  categoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryText: {
    ...TypographyThemes.nunito.body,
    fontSize: 13,
    fontWeight: '700',
    color: Colors.white,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 8,
    paddingLeft: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  infoLabel: {
    ...TypographyThemes.nunito.body,
    fontSize: 14,
    color: Colors.text.secondary,
    flex: 1,
    marginRight: 12,
  },
  infoValue: {
    ...TypographyThemes.nunito.body,
    fontSize: 14,
    color: Colors.text.primary,
    fontWeight: '500',
    flex: 1,
    textAlign: 'right',
  },
  lastInfoRow: {
    borderBottomWidth: 0,
  },
  billingInfo: {
    backgroundColor: Colors.blue[50],
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: Colors.blue[200],
  },
  billingTitle: {
    ...TypographyThemes.nunito.body,
    fontSize: 14,
    fontWeight: '600',
    color: Colors.blue[700],
    marginBottom: 8,
  },
  billingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
  },
  billingLabel: {
    ...TypographyThemes.nunito.body,
    fontSize: 13,
    color: Colors.blue[600],
  },
  billingValue: {
    ...TypographyThemes.nunito.body,
    fontSize: 13,
    color: Colors.blue[800],
    fontWeight: '600',
  },
  hasImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.green[50],
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.green[200],
    gap: 6,
  },
  hasImageText: {
    ...TypographyThemes.nunito.body,
    fontSize: 12,
    color: Colors.green[600],
    fontWeight: '600',
  },
  noImageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.gray[50],
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.gray[200],
    gap: 6,
  },
  noImageText: {
    ...TypographyThemes.nunito.body,
    fontSize: 12,
    color: Colors.gray[500],
    fontWeight: '500',
  },
  viewImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: Colors.blue[50],
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Colors.blue[200],
    gap: 6,
  },
  viewImageButtonText: {
    ...TypographyThemes.nunito.body,
    fontSize: 12,
    color: Colors.blue.primary,
    fontWeight: '600',
  },
  viewImageButtonDisabled: {
    backgroundColor: Colors.gray[100],
    borderColor: Colors.gray[300],
  },
  viewImageButtonTextDisabled: {
    color: Colors.gray[500],
  },
  buttonContainer: {
    paddingBottom: 20,
    alignItems: 'center',
  },
  buttonConfirm: {
    width: '100%',
  },
});