import Colors from "@/src/constants/Colors";
import { TypographyThemes } from "@/src/constants/Fonts";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    fontSize: 25,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  scrollContent: {
    paddingBottom: 20,
    flexGrow: 1,
  },
  infoContainer: {
    marginTop: 15,
    marginBottom: 28,
    padding: 20,
    backgroundColor: Colors.blue.primary,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.blue.light,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  infoIconContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 8,
    marginRight: 12,
  },
  infoTitle: {
    ...TypographyThemes.poppins.subtitle,
    fontWeight: '700',
    color: Colors.white,
  },
  infoDescription: {
    ...TypographyThemes.nunito.bodySmall,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 22,
  },

  // Seção principal
  sectionContainer: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: Colors.blue.light,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  sectionTitle: {
    ...TypographyThemes.poppins.title,
    color: Colors.text.primary,
    marginBottom: 20,
  },

  // Campos de input
  inputContainer: {
    marginBottom: 24,
  },
  inputLabel: {
    ...TypographyThemes.inter.subtitle,
    marginBottom: 12,
    color: Colors.text.primary,
    fontWeight: '600',
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  label: {
    ...TypographyThemes.inter.subtitle,
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text.primary,
    flex: 1,
  },
  numericInput: {
    width: 100,
    height: 60,
    textAlign: "center",
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.gray.light,
    paddingHorizontal: 16,
    ...TypographyThemes.openSans.input,
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text.primary,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    // Remove traços e underline
    textDecorationLine: 'none',
    borderBottomWidth: 0,
    // Melhorias visuais
    letterSpacing: 1,
  },
  inputFocused: {
    borderColor: Colors.blue.primary,
    borderWidth: 2,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    backgroundColor: Colors.white,
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text.primary,
    textDecorationLine: 'none',
    borderBottomWidth: 1.5,
    letterSpacing: 1,
  },
  inputWithText: {
    borderColor: Colors.blue.primary,
    borderWidth: 1.5,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    backgroundColor: Colors.white,
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text.primary,
    textDecorationLine: 'none',
    borderBottomWidth: 0,
    letterSpacing: 1,
  },
  inputWithPlaceholder: {
    borderColor: Colors.gray.light,
    borderWidth: 1.5,
    backgroundColor: Colors.white,
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text.primary,
    textDecorationLine: 'none',
    borderBottomWidth: 0,
    letterSpacing: 1,
  },
  unitContainer: {
    backgroundColor: Colors.blue.light,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.blue.light,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  unitText: {
    ...TypographyThemes.inter.label,
    color: Colors.white,
    fontWeight: '700',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  optionalText: {
    ...TypographyThemes.nunito.caption,
    color: Colors.white,
    marginTop: 20,
    backgroundColor: Colors.blue.primary,
    padding: 10,
    borderRadius: 8,
    lineHeight: 16,
  },
  button: {
    marginTop: 10,
  },
  primaryButton: {
    width: "100%",
  },
  separator: {
    height: 1,
    backgroundColor: Colors.blue.primary,
    marginVertical: 20,
  },
});
