import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  formContainer: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 16,
    marginTop: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.text.primary,
    marginTop: 5,
    marginBottom: 12,
  },
  emptyProductsText: {
    fontSize: 14,
    color: Colors.text.tertiary,
    fontStyle: "italic",
    textAlign: "center",
    textDecorationLine: "underline",
  },
  actionButtonsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
    marginBottom: 12,
  },
  addProductButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.blue.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  addProductButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: Colors.white,
  },
  scanButton: {
    backgroundColor: Colors.green[500],
    width: 56,
    height: 56,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.green[500],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  scanButtonDisabled: {
    backgroundColor: Colors.gray[400],
    shadowOpacity: 0.1,
    elevation: 2,
  },
  productsListContainer: {
    flex: 1,
    marginTop: 8,
  },
  productsScrollView: {
    flex: 1,
  },
  productsListContent: {
    paddingBottom: 8,
  },
  productsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: 8,
  },
  productCardWrapper: {
    width: "30%",
    minWidth: 110,
  },
  expandedProductCardWrapper: {
    width: "100%",
  },
  productCard: {
    backgroundColor: Colors.background.secondary,
    borderRadius: 8,
    padding: 15,
    paddingTop: 20,
    elevation: 2,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    borderLeftWidth: 4,
    borderLeftColor: Colors.blue.primary,
  },
  expandedProductCard: {
    borderRadius: 12,
    padding: 12,
    borderLeftWidth: 4,
    borderLeftColor: Colors.blue.primary,
  },
  productCardHeader: {
    position: "relative",
    marginBottom: 8,
  },
  productCardTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.text.primary,
    textAlign: "left",
    paddingRight: 20,
  },
  expandedProductCardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text.primary,
    textAlign: "center",
    paddingRight: 0,
  },
  productExpandButton: {
    position: "absolute",
    top: -15,
    right: -10,
    padding: 4,
    borderRadius: 4,
    backgroundColor: Colors.background.secondary,
    elevation: 1,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    zIndex: 1,
  },
  productCardValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.text.primary,
    textAlign: "left",
    marginBottom: 4,
  },
  expandedProductCardValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.text.primary,
    textAlign: "center",
    marginBottom: 4,
  },
  productCardQuantity: {
    fontSize: 12,
    color: Colors.text.secondary,
    textAlign: "left",
  },
  expandedProductDetails: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.border.light,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 6,
  },
  productDetailTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text.primary,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textAlign: "center",
    width: "100%",
  },
  productDetailRow: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: Colors.background.primary,
    borderRadius: 6,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: Colors.border.light,
    width: "48%",
    minWidth: 120,
    minHeight: 50,
  },
  productDetailLabel: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.text.secondary,
    marginBottom: 2,
    textAlign: "left",
  },
  productDetailValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text.primary,
    textAlign: "center",
    flex: 1,
    justifyContent: "center",
    marginTop: 2,
  },
  productItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: Colors.gray[50],
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Colors.gray[200],
  },
  productInfo: {
    flex: 1,
  },
  productName: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text.primary,
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.text.secondary,
  },
  productControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.border.light,
    position: "relative",
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
  },
  quantityButton: {
    backgroundColor: Colors.blue.primary,
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  quantityButtonDisabled: {
    backgroundColor: Colors.gray[300],
  },
  quantityText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.text.primary,
    minWidth: 20,
    textAlign: "center",
  },
  removeButton: {
    position: "absolute",
    right: 0,
    marginTop: 8,
    padding: 6,
  },
  bottomContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.gray[200],
  },
  totalSection: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  totalLabel: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.text.primary,
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.blue.primary,
  },
  finalizeButton: {
    height: 56,
    maxWidth: "50%",
    alignSelf: "flex-end",
    borderRadius: 16,
    backgroundColor: Colors.blue.primary,
    paddingHorizontal: 24,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: Colors.blue.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  finalizeButtonDisabled: {
    backgroundColor: Colors.gray[400],
    shadowOpacity: 0.1,
    elevation: 2,
  },
  finalizeButtonText: {
    color: Colors.white,
    fontWeight: "600",
    fontSize: 16,
  },
});
