import Colors from "@/src/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    backgroundColor: Colors.gray.zinc,
    height: 120,
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomRightRadius: 70,
    paddingHorizontal: 10,
  },
  brandContainer: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginBottom: 10,
  },
  brandMain: {
    fontSize: 35,
    fontWeight: "bold",
    color: Colors.gray.light,
    textTransform: "uppercase",
    marginRight: 5,
  },
  brandSub: {
    fontSize: 21,
    color: Colors.gray.light,
    marginBottom: 5,
  },
  iconCircle: {
    width: 50,
    height: 50,
    borderRadius: 30,
    backgroundColor: Colors.gray.zinc,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    marginBottom: 10,
  },
  body: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 20,
  },
  parkingStatus: {
    height: "35%",
    width: "80%",
    alignItems: "center",
    backgroundColor: Colors.white,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  BoxHeader: {
    width: "100%",
    height: 45,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  title: {
    fontFamily: "Roboto_600SemiBold",
    fontSize: 27,
  },
  refreshIcon: {
    width: 35,
    height: 35,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.blue.logo,
  },
  parkingContent: {
    flex: 1,
    width: "100%",
    flexDirection: "column",
  },
  statusParking: {
    flex: 3,
    flexDirection: "row",
    width: "100%",
  },
  freeParking: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  numberFree: {
    fontFamily: "Roboto_700Bold",
    fontSize: 50,
    color: Colors.green.dark,
  },
  labelFree: {
    fontFamily: "Roboto_600SemiBold",
    fontSize: 18,
    color: Colors.green.dark,
    marginTop: -10,
  },
  usedParking: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  numberUsed: {
    fontFamily: "Roboto_700Bold",
    fontSize: 50,
    color: Colors.red.dark,
  },
  labelUsed: {
    fontFamily: "Roboto_600SemiBold",
    fontSize: 18,
    color: Colors.red.dark,
    marginTop: -10,
  },
  detailsParking: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 15,
  },
  dividerVertical: {
    width: 1,
    height: "60%", // altura proporcional ao container
    backgroundColor: Colors.gray.light,
    alignSelf: "center",
    marginHorizontal: 8,
  },
  iconDescriptionRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 5,
  },
  iconText: {
    fontSize: 12,
    marginLeft: 4,
  },
  bottomBar: {
    height: "16%",
    width: "100%",
    backgroundColor: Colors.gray.zinc,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: Colors.gray.light,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderTopRightRadius: 42,
    borderTopLeftRadius: 42,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  buttonEntry: {
    width: 50,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    backgroundColor: Colors.green.dark,
  },
  buttonExit: {
    width: 50,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    backgroundColor: Colors.red.dark,
  },
  buttonPatio: {
    width: 50,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    backgroundColor: Colors.blue.dark,
  },
});
