import Colors from "@/src/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  heroImage: {
    position: "absolute",
    top: 80,
    right: -270,
    width: "130%",
    height: "95%",
    transform: [{ scaleX: -1 }],
    resizeMode: "cover",
    opacity: 0.1,
    zIndex: -1,
  },
  mainInfoCard: {
    backgroundColor: Colors.background.secondary,
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    marginHorizontal: 4,
    elevation: 8,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border.light,
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  mainInfoTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.text.primary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
    flex: 1,
  },
  expandButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: Colors.background.primary,
    elevation: 2,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: Colors.background.primary,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border.light,
    elevation: 2,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  infoLabel: {
    fontSize: 15,
    color: Colors.text.secondary,
    fontWeight: "600",
    flex: 1,
  },
  infoValue: {
    fontSize: 15,
    color: Colors.text.primary,
    fontWeight: "700",
    textAlign: "right",
    flex: 1,
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  statusBadge: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 30,
    flexDirection: "row",
    alignItems: "center",
    elevation: 4,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  statusOpen: {
    backgroundColor: Colors.button.success + "20",
    borderWidth: 1,
    borderColor: Colors.button.success,
  },
  statusClosed: {
    backgroundColor: Colors.button.danger + "20",
    borderWidth: 1,
    borderColor: Colors.button.danger,
  },
  statusNotCreated: {
    backgroundColor: Colors.gray[400] + "20",
    borderWidth: 1,
    borderColor: Colors.gray[400],
  },
  statusText: {
    fontSize: 14,
    fontWeight: "700",
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  statusTextOpen: {
    color: Colors.button.success,
  },
  statusTextClosed: {
    color: Colors.button.danger,
  },
  statusTextNotCreated: {
    color: Colors.gray[400],
  },
  miniCardsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  miniCard: {
    backgroundColor: Colors.background.secondary,
    borderRadius: 8,
    padding: 15,
    paddingTop: 20,
    marginHorizontal: 5,
    marginBottom: 10,
    elevation: 2,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    // Estado normal: 3 cards em linha
    width: "30%",
    minWidth: 100,
  },
  expandedCard: {
    // Estado expandido: largura total
    width: "96%",
    marginBottom: 25,
    marginHorizontal: "2%",
    borderRadius: 16,
    padding: 20,
  },
  expandedCardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text.primary,
    textAlign: "center",
    paddingRight: 0,
  },
  miniCardHeader: {
    position: "relative",
    marginBottom: 8,
  },
  miniCardTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.text.primary,
    textAlign: "left",
    paddingRight: 20,
  },
  miniExpandButton: {
    position: "absolute",
    top: -15,
    right: -10,
    padding: 4,
    borderRadius: 4,
    backgroundColor: Colors.background.secondary,
    elevation: 1,
    shadowColor: Colors.shadow.light,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    zIndex: 1,
  },
  miniCardValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.text.primary,
    textAlign: "left",
    marginBottom: 4,
  },
  miniCardQuantity: {
    fontSize: 12,
    color: Colors.text.secondary,
    textAlign: "left",
  },
  expandedCardValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: Colors.text.primary,
    textAlign: "center",
    marginBottom: 4,
  },
  expandedCardQuantity: {
    fontSize: 12,
    color: Colors.text.secondary,
    textAlign: "center",
  },
  vehiclesCard: {
    borderLeftWidth: 4,
    borderLeftColor: Colors.button.primary,
  },
  productsCard: {
    borderLeftWidth: 4,
    borderLeftColor: Colors.button.warning,
  },
  expensesCard: {
    borderLeftWidth: 4,
    borderLeftColor: Colors.button.danger,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 16,
    color: Colors.text.secondary,
    marginTop: 10,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  errorText: {
    fontSize: 16,
    color: Colors.button.danger,
    textAlign: "center",
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: Colors.button.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: Colors.text.inverse,
    fontSize: 14,
    fontWeight: "600",
  },
  expandedDetails: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.border.light,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
  },
  detailTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text.primary,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  detailRow: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    paddingVertical: 5,
    paddingHorizontal: 8,
    backgroundColor: Colors.background.primary,
    borderRadius: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: Colors.border.light,
    width: "48%",
    minWidth: 140,
    minHeight: 65,
  },
  detailRowFull: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: Colors.background.primary,
    borderRadius: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: Colors.border.light,
    width: "100%",
    minHeight: 60,
  },
  detailLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.text.secondary,
    marginBottom: 4,
    textAlign: "left",
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text.primary,
    textAlign: "center",
    flex: 1,
    justifyContent: "center",
    marginTop: 5,
  },
});
